
default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:197899717102:android:e00eaec375e360d230a6ff",
        firebase_cli_token: "1//03RVXnhdNPDHKCgYIARAAGAMSNwF-L9IrKBKbeZq-mwNL9_goHVB-jsg7iiGWr2raIKKsGArEXH_mTJxaxNxu6H-Ah3QbFCmqfwY",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "ahmedkhedr5p@gmail.com",
        release_notes: "First Fastlane Firebase App Distribution Release"
      )
  end
end
